EXPERIMENT: "MK_all"
GRANULARITY: ["site-MutSel-0.0025", "site-MutSelExclu-0.0025", "site-Classical-0.0025"]
SUBSAMPLING_SITES: -1
SUBSAMPLING_GENES: -1
NBR_BATCHES: 0
NBR_REPLICATES_PER_BATCH: 0
SUBSAMPLING_WEIGHTED: false
SAMPLE_LIST: "sample_all.tsv"
SFS: ["unfolded"]
DFE_MODELS: ["MK"]
