GRANULARITY: ["gene", "site"]
SUBSAMPLING_SITES: -1
SUBSAMPLING_GENES: -1
NBR_REP: 4
NBR_BATCHES: 1
SUBSAMPLING_WEIGHTED: true
NBR_BINS: 3
NBR_REPETITIONS_PER_BIN: 2
SAMPLE_LIST: "sample_SK.tsv"
SFS: ["unfolded", "folded"]
DFE_MODELS: ["grapes"]
# DFE_MODELS: ["dfem", "grapes", "polyDFE"]
