EXPERIMENT: "MK_control"
GRANULARITY: ["gene", "site", "site_strong"]
SUBSAMPLING_SITES: -1
SUBSAMPLING_GENES: -1
NBR_BATCHES: 1
NBR_REPLICATES_PER_BATCH: 10
SUBSAMPLING_WEIGHTED: true
SAMPLE_LIST: "sample_all.tsv"
SFS: ["unfolded"]
DFE_MODELS: ["MK"]
