GRANULARITY: ["gene", "site"]
SUBSAMPLING_SITES: -1
SUBSAMPLING_GENES: -1
NBR_REP: 50
NBR_BATCHES: 20
SUBSAMPLING_WEIGHTED: true
GATHER_SFS: false
NBR_BINS: 0
NBR_REPETITIONS_PER_BIN: 0
SAMPLE_LIST: "sample_superpop.tsv"
SFS: ["unfolded", "folded"]
DFE_MODELS: ["grapes", "polyDFE", "MK"]
# DFE_MODELS: ["dfem", "grapes", "polyDFE"]
