EXPERIMENT: "ontology"
GRANULARITY: ["gene-MutSel-0.025", "site-MutSel-0.025", "site-MutSelExclu-0.025", "site-Classical-0.025"]
SUBSAMPLING_SITES: -1
SUBSAMPLING_GENES: -1
NBR_BATCHES: 0
NBR_REPLICATES_PER_BATCH: 0
SUBSAMPLING_WEIGHTED: false
SAMPLE_LIST: "sample_all.tsv"
SFS: []
DFE_MODELS: []
