FTP: 'ftp.1000genomes.ebi.ac.uk'
STUDY: '/vol1/ftp/data_collections/1000G_2504_high_coverage/working/'
CHR_PREFIX: "chr"
CONTAINS_PREFIX: 'CCDG_13607_B01_GRM_WGS_2019-02-19_'
CONTAINS: '.recalibrated_variants.vcf.gz'
ASSEMBLY: "GRCh38"
SPECIES: "Homo_sapiens"
PANEL: "integrated_call_samples_v3.20130502.SUPERPOP.tsv"
DOWNLOAD:
  Homo_sapiens.GRCh38.gtf.gz: "ftp.ensembl.org/pub/release-91/gtf/homo_sapiens/Homo_sapiens.GRCh38.91.gtf.gz"
  Homo_sapiens.GRCh38.fa.gz: "ftp.ensembl.org/pub/release-91/fasta/homo_sapiens/cds/Homo_sapiens.GRCh38.cds.all.fa.gz"