FTP: 'ftp.1000genomes.ebi.ac.uk'
STUDY: '/vol1/ftp/data_collections/1000G_2504_high_coverage/working/'
CHR_PREFIX: "chr"
CONTAINS_PREFIX: 'CCDG_13607_B01_GRM_WGS_2019-02-19_'
CONTAINS: '.recalibrated_variants.vcf.gz'
ASSEMBLY: "GRCh38"
ENSEMBL_RELEASE: 91
SPECIES: "Homo_sapiens"
PANEL: "integrated_call_samples_v3.20130502.SUPERPOP.tsv"
