FTP: 'ftp.ebi.ac.uk'
STUDY: '/pub/databases/nextgen/capra/variants/'
CONTAINS_PREFIX: ""
CONTAINS: '.genus_snps.CHIR1_0'
ASSEMBLY: "ARS1"
ENSEMBL_RELEASE: 92
SPECIES: "Capra_hircus"
LIFT_OVER_DBSNP: "GCA_000317765.1_current_ids.vcf.gz"
LIFT_OVER_ENSEMBL: "capra_hircus.vcf.gz"
