FTP: 'ftp.ebi.ac.uk'
STUDY: '/pub/databases/nextgen/capra/variants/'
CONTAINS_PREFIX: ""
CONTAINS: '.genus_snps.CHIR1_0'
ASSEMBLY: "ARS1"
SPECIES: "Capra_hircus"
CHR2ACC: "chr2acc"
DOWNLOAD:
  Capra_hircus.ARS1.gtf.gz: "ftp.ncbi.nlm.nih.gov/genomes/all/annotation_releases/9925/102/GCF_001704415.1_ARS1/GCF_001704415.1_ARS1_genomic.gtf.gz"
  Capra_hircus.ARS1.fa.gz: "ftp.ncbi.nlm.nih.gov/genomes/all/annotation_releases/9925/102/GCF_001704415.1_ARS1/GCF_001704415.1_ARS1_cds_from_genomic.fna.gz"
  liftover_source.vcf.gz: "ftp.ebi.ac.uk/pub/databases/eva/rs_releases/release_2/by_species/capra_hircus/CHIR_1.0/GCA_000317765.1_current_ids.vcf.gz"
  liftover_target.vcf.gz: "ftp.ensembl.org/pub/release-92/variation/vcf/capra_hircus/capra_hircus.vcf.gz"
