FTP: 'ftp.1000genomes.ebi.ac.uk'
STUDY: 'vol1/ftp/release/'
CONTAINS: 'phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes'
NAME: "Homo_sapiens.GRCh38"
ENSEMBL_RELEASE: 91
SPECIES: "homo_sapiens"
PANEL: "integrated_call_samples_v3.20130502.ALL.panel"