SAMPLE_LIST: "sample_all.tsv"
METHOD_LIST: [ "MutSel" ]
# METHOD_LIST: [ "MutSel", "Omega", "SW", "WS", "SIFT" ]
SIFT:
  Bos_taurus: "Bos_taurus.UMD3.1.SIFT.vcf.gz"
  Ovis_aries: "Ovis_aries.Oar_v3.1.SIFT.vcf.gz"
  Capra_hircus: "Capra_hircus.ARS1.SIFT.vcf.gz"
  Canis_familiaris: "Canis_familiaris.CanFam3.1.SIFT.vcf.gz"
  # Equus_caballus: "Equus_caballus.EquCab2.SIFT.vcf.gz"
  # Homo_sapiens: "Homo_sapiens.GRCh38.SIFT.vcf.gz"